name: $(date:yyyyMMdd)$(rev:-rr)

resources:
  repositories:
    - repository: templates
      endpoint: wieslawsoltes
      type: github
      name: wieslawsoltes/BuildTemplates
      ref: refs/tags/v2.0.0

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  PublishFramework: 'net8.0'
  PublishProject: 'DockMvvmSample'
  PublishRuntime: ''
  Workloads: 'wasm-tools wasm-experimental'

jobs:
  - template: Test-PowerShell.yml@templates
    parameters:
      name: 'Test_Windows'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}

  - template: Test-Bash.yml@templates
    parameters:
      name: 'Test_Linux'
      vmImage: 'ubuntu-20.04'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}

  - template: Test-Bash.yml@templates
    parameters:
      name: 'Test_macOS'
      vmImage: 'macOS-14'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}

  - template: Pack-MyGet.yml@templates
    parameters:
      name: 'Pack_MyGet'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}

  - template: Pack-NuGet.yml@templates
    parameters:
      name: 'Pack_NuGet'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}

  - template: Publish-PowerShell.yml@templates
    parameters:
      name: 'Publish_Windows'
      vmImage: 'windows-2022'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'win-x64'

  - template: Publish-Bash.yml@templates
    parameters:
      name: 'Publish_Linux'
      vmImage: 'ubuntu-20.04'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'linux-x64'

  - template: Publish-Bash.yml@templates
    parameters:
      name: 'Publish_macOS_x64'
      vmImage: 'macOS-14'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'osx-x64'

  - template: Publish-Bash.yml@templates
    parameters:
      name: 'Publish_macOS_arm64'
      vmImage: 'macOS-14'
      BuildConfiguration: ${{ variables.BuildConfiguration }}
      Workloads: ${{ variables.Workloads }}
      PublishFramework: ${{ variables.PublishFramework }}
      PublishProject: ${{ variables.PublishProject }}
      PublishRuntime: 'osx-arm64'
