name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:

  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macOS-10.14]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview7-012821
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
    - name: Pack
      if: github.event_name != 'pull_request'
      run: dotnet pack -c Release -o ./artifacts/NuGet
    - name: Artifacts
      if: github.event_name != 'pull_request' && matrix.os == 'windows-2019'
      uses: actions/upload-artifact@master
      with:
        name: NuGet
        path: ./artifacts/NuGet

  publish-windows:
    name: Publish windows-2019
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview7-012821
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release -f netcoreapp3.0 -r win7-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-win7-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp3.0 -r win7-x64 -o ./artifacts/AvaloniaDemo.Experimental-netcoreapp3.0-win7-x64 ./samples/AvaloniaDemo.Experimental/AvaloniaDemo.Experimental.csproj
        dotnet publish -c Release -f netcoreapp3.0 -r win7-x64 -o ./artifacts/AvaloniaDemo.Perspectives-netcoreapp3.0-win7-x64 ./samples/AvaloniaDemo.Perspectives/AvaloniaDemo.Perspectives.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.0-win7-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.0-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo.Experimental-netcoreapp3.0-win7-x64
        path: ./artifacts/AvaloniaDemo.Experimental-netcoreapp3.0-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo.Perspectives-netcoreapp3.0-win7-x64
        path: ./artifacts/AvaloniaDemo.Perspectives-netcoreapp3.0-win7-x64

  publish-ubuntu:
    name: Publish ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview7-012821
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release -f netcoreapp3.0 -r debian.8-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-debian.8-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
        dotnet publish -c Release -f netcoreapp3.0 -r ubuntu.14.04-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.0-debian.8-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.0-debian.8-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.0-ubuntu.14.04-x64

  publish-macOS:
    name: Publish macOS-10.14
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview7-012821
    - name: Publish
      if: github.event_name != 'pull_request'
      run: dotnet publish -c Release -f netcoreapp3.0 -r osx.10.12-x64 -o ./artifacts/AvaloniaDemo-netcoreapp3.0-osx.10.12-x64 ./samples/AvaloniaDemo/AvaloniaDemo.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaDemo-netcoreapp3.0-osx.10.12-x64
        path: ./artifacts/AvaloniaDemo-netcoreapp3.0-osx.10.12-x64
